<style>

.fader {
   background-color: transparent;

   transition: background-color 1s linear;
   -moz-transition: background-color 1s linear;
   -webkit-transition: background-color 1s linear;
   -ms-transition: background-color 1s linear;
}

.highlightItem {
   background-color: #bfbfbf;
}

</style>

<header id="header" class="ex-header">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <h1><?php echo($this->title); ?></h1>
            </div>
        </div>
    </div>
</header>
<div class="ex-basic-1">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="breadcrumbs">
                    <a href="/#contact">Home</a><i class="fa fa-angle-double-right"></i><span><?php echo($this->title); ?></span>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="ex-basic-2">
    <div class="container">
        <ul class="list-unstyled">
            <?php foreach($this->entries as $key => $entry): ?>
            <li id="item-<?php echo($key);?>" class="media mb-4 <?php if($this->highlightId == $entry['id']):?>highlightItem fader<?php endif;?>">
                <h3 class="d-none d-md-block" style="min-width: 89px;">Nr. <?php echo($entry['nb']); ?></h3>
                <div class="media-body" style="border-left: 1px solid #929292; padding-left: 12px;">
                    <h3 class="mt-0 mb-1">Eintrag von <?php echo($entry['author']); ?></h3>
                    <small style="font-style: italic;">
                        <div>Erstellt am  <?php echo($entry['date']); ?> </div>
                    </small>
                    <?php echo($entry['message']); ?>
                </div>
            </li>
            <?php endforeach; ?>
        </ul>
    </div>
</div>

<?php /*
<button
    type="button"
    class="btn btn-danger btn-sm"
    data-toggle="modal"
    data-target="#deleteDialogModal"
    data-url="<?php echo($this->getCurrentPath()); ?>"
    data-form-id="<?php echo($this->getPathSimplified()); ?>"
    data-item-id="<?php echo($entry['id']); ?>"
>löschen</button>
 *
 */ ?>
<div class="ex-basic-1">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="breadcrumbs">
                    <a href="/#contact">Home</a><i class="fa fa-angle-double-right"></i><span><?php echo($this->title); ?></span>
                </div>
            </div>
        </div>
    </div>
</div>

