    <header id="header" class="ex-header">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <h1>Gästebucheintrag freischalten / löschen</h1>
                </div>
            </div>
        </div>
    </header>
    <div class="ex-basic-1">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="breadcrumbs">
                        <a href="/">Home</a><i class="fa fa-angle-double-right"></i><span>Gästebucheintrag freischalten / löschen</span>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <?php if($this->confirm): ?>
    <div class="ex-basic-2">
        <div class="container">
            <div class="row">
                <div class="col-sm">
                </div>
                <div class="col-sm">
                    <div class="card" style="width: 38rem;">
                        <div class="card-body">
                            <h5 class="card-title">Soll folgender Gästebuch endgültig gelöscht werden?</h5>
                            <small style="font-style: italic;">
                                <div style=" margin-bottom: 12px;">Eintrag von <?php echo($this->entry['Author']); ?>. Erstellt am <?php echo($this->entry['CreationDate']); ?></div>
                            </small>
                            <p class="card-text"><?php echo($this->entry['Message']); ?></p>
                            <a href="<?php echo($this->urlDelete);?>" class="btn btn-danger" style="text-decoration: none">Eintrag endgültig löschen</a>
                        </div>
                    </div>
                </div>
                <div class="col-sm">
                </div>
            </div>
        </div>
    </div>
    <?php else: ?>
    <div class="ex-basic-2">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="alert alert-<?php if($this->error): ?>danger<?php else: ?>primary<?php endif; ?>" role="alert" style="margin-top: 100px; margin-bottom: 150px;" >
                        <?php echo($this->text); ?>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <?php endif; ?>
    <div class="ex-basic-1">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="breadcrumbs">
                        <a href="/">Home</a><i class="fa fa-angle-double-right"></i><span>Gästebucheintrag freischalten / löschen</span>
                    </div>
                </div>
            </div>
        </div>
    </div>
